### ISSUE TITLE
Installing and testing gazebo11 leads to error

### ISSUE THREAD

**Issue by nkalupahana** [osrf/homebrew-simulation#1543]
Currently, I'm running the following simplified workflow on GitHub Actions:
```
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Install
        run: |
          brew tap osrf/simulation
          brew update
          brew install osrf/simulation/gazebo11
          brew test osrf/simulation/gazebo11
```

However, I keep running into the following error when running the `test` command: https://github.com/nkalupahana/ros2-foxy-macos/runs/3196791174?check_suite_focus=true

This just started last night, and it worked the night before, so any insight into why this might be happening would be appreciated.

**Comment by traversaro** [comment]
The critical message there is "Reinstalling 1 broken dependent from source", it tipically happens when gazebo's dependency break for some reason, see similar issues from the path:
* https://github.com/osrf/homebrew-simulation/issues/1350
* https://github.com/osrf/homebrew-simulation/issues/1439
* https://github.com/osrf/homebrew-simulation/issues/1489

**Comment by traversaro** [comment]
Thanks a lot @scpeters, after https://github.com/osrf/homebrew-simulation/pull/1545 the issue is solved for me.

**Comment by nkalupahana** [comment]
Yep, my builds are now passing as well.
